### ISSUE TITLE
Package Bolt as a Snap installation 

### ISSUE THREAD

**Issue by VestigeJ** [puppetlabs/bolt#1103]
Feature Request

Snap packages (akin to Flatpaks) are a great way to simplify installation across a wide array of Linux distributions. I'm making note of this as a feature request - but I may also be the one to submit a PR for it down the road.

**Comment by lucywyman** [comment]
Hi @VestigeJ - this is something we've been thinking about for a few months now and haven't prioritized. It looks like Puppet doesn't currently ship any packages as Snaps, so the first step for us is to determine how much work it will be to start shipping them. From there we'll decide if that fits into our current roadmap.

I'll keep you updated with what we find, and whether we plan to start shipping Snaps or not. Thanks for your patience!

CC @donoghuc

**Comment by beechtom** [comment]
Using the `puppet-tools-release-bionic.deb` package and the following `snapcraft.yaml` config successfully creates a snap.

```
name: bolt
version: '1.0'
summary: Execute commands remotely over SSH and WinRM.
description: |
  Bolt is a Ruby command-line tool for executing commands, scripts, and tasks on remote systems using SSH and WinRM.

base: core18

grade: devel
confinement: devmode

parts:
    bolt:
        plugin: nil
        override-build: |
            wget https://apt.puppet.com/puppet-tools-release-bionic.deb
            dpkg -i puppet-tools-release-bionic.deb
            apt update
            apt install -y puppet-bolt

apps:
    bolt:
        command: bolt
```

When building the snap and shelling into the snap, you can run `bolt` commands as expected. 

```
snapcraft --shell-after
```

However, when installing the snap, the `bolt` command is not recognized. When shelling into the snap the executable can be found at `/usr/local/bin/bolt`, but when installing the snap it's no longer at this path or `$SNAP/usr/local/bin/bolt`.

**Comment by VestigeJ** [comment]
I might be wrong but this might be intended behavior given the AppArmor around snaps. I think the installation method that exposes the bolt command would require the —classic flag to be passed on snap install. That will reduce the confinement of the snap being installed.

**Comment by beechtom** [comment]
So I've got a snapcraft file that successfully installs everything, but there are issues actually executing bolt.

This is the `snapcraft.yaml`

```yaml
name: bolt
version: '1.0'
summary: Execute commands remotely over SSH and WinRM.
description: |
  Bolt is a Ruby command-line tool for executing commands, scripts, and tasks on remote systems using SSH and WinRM.

base: core18

# These values would change for an actual release
grade: devel
confinement: devmode

parts:
  bolt:
    plugin: nil
    # This fixes some issues with ffi
    build-attributes: [keep-execstack]
    # Manually download the deb archive and install
    override-build: |
      wget https://apt.puppet.com/puppet-tools-release-bionic.deb
      dpkg -i puppet-tools-release-bionic.deb
      apt-get update
      apt-get install -y puppet-bolt
    # Snapcraft builds the snap in a vm and installs at the expected location,
    # so this moves it to the install directory
    organize:
      '/opt/*' : bin/

# This tells the snap to execute bolt when we use the 'bolt' command
apps:
  bolt:
    command: bin/puppetlabs/bolt/bin/bolt
```

To get this all working, install `snapcraft` and `multipass`. Snap should already be installed on Ubuntu and a few other distros.

- `sudo apt install snap`
- `sudo snap install snapcraft --classic`
- `sudo snap install multipass --classic --beta`

Build the snap from `snapcraft.yaml`

- `snapcraft`

You should now have a file named `bolt_1.0_amd64.snap`.

Boot up a VM using multipass, copy the snap package to it (note the `:` at the end of the command), and shell into the VM.

- `multipass launch --name testvm`
- `multipass copy-files bolt_1.0_amd64.snap testvm:`
- `multipass shell testvm`

Install the snap package.

- `sudo snap install bolt_1.0_amd64.snap --devmode`

You should get a message saying the snap was installed. You can confirm by looking for `/snap/bolt`. Since the `snapcraft.yaml` file has an app named `bolt` that runs the `bolt` command, this *should* run bolt. However, doing so results in the following error.

```
/snap/bolt/x1/command-bolt.wrapper: 2: exec: /snap/bolt/x1/bin/puppetlabs/bolt/bin/bolt: not found
```

View the contents of `command-bolt.wrapper`.

```bash
#!/bin/sh
exec "$SNAP/bin/puppetlabs/bolt/bin/bolt" "$@"
```

`$SNAP` just expands to `/snap/bolt/x1`. What's weird is the file that supposedly isn't found *does* exist. You can run the following command, which runs the bolt script but results in an error.

```bash
$ /snap/bolt/x1/bin/puppetlabs/bolt/bin/bolt

-bash: /snap/bolt/x1/bin/puppetlabs/bolt/bin/bolt: /opt/puppetlabs/bolt/bin/ruby: bad interpreter: No such file or directory
```

This is because of the shebang in the bolt script, which says the ruby interpreter is in `/opt/...`

```bash
#!/opt/puppetlabs/bolt/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'bolt' is installed as part of a gem, and
# this file is here to facilitate running it.
#

...
```

I've tried replacing this by adding a sed line to the build-override, but that causes another error with the ruby interpreter because it can't find shared libraries.

```yaml
    override-build: |
      wget https://apt.puppet.com/puppet-tools-release-bionic.deb
      dpkg -i puppet-tools-release-bionic.deb
      apt-get update
      apt-get install -y puppet-bolt
      sed -i -e 's+opt/puppetlabs/bolt/bin/ruby+snap/bolt/x1/bin/puppetlabs/bolt/bin/ruby+g' /opt/puppetlabs/bolt/bin/bolt

```

```bash
$ /snap/bolt/x1/bin/puppetlabs/bolt/bin/bolt

/snap/bolt/x1/bin/puppetlabs/bolt/bin/ruby: error while loading shared libraries: libruby.so.2.5: cannot open shared object file: No such file or directory
```

The issue I'm not sure how to solve is that bolt installs at `/opt`, but a snap package doesn't seem to have a way to install at that location (at least I'm not finding any documentation on it). This all seems to stem from the fact that when the snap is installed, it only installs files that are in the `install` directory when you build the snap package. 

I'm wondering if there is a better way to approach building the snap from a deb, or if we should explore building from scratch: https://snapcraft.io/first-snap/ruby
