### ISSUE TITLE
Bolt will not retrieve tasks over PCP

### ISSUE THREAD

**Issue by bryanjbelanger** [puppetlabs/bolt#1139]
## Describe the Bug

When running 'bolt task show' over pcp I only get a list of local tasks.

## Expected Behavior
I expect to get a list of tasks in Puppet Enterprise.

## Steps to Reproduce

bolt.yaml looks similar to this:

``` yaml
transport: pcp
  cacert: <path to cert>
  token-file: <path to token>
  service-url: <pe service url> 
```

I run the bolt show task.

```cli
bolt task show
```
or

```cli
bolt task show --transport pcp
```

## Environment
 - Version [1.27.0]
 - Platform [PE 2018.1]

## Additional Context

N/A
