### ISSUE TITLE
Add Azure inventory plugin

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#1148]
## Use Case
Users should be able to run Bolt commands on Azure virtual machines and virtual machine scale sets without manually adding them to the inventory.

## Describe the Solution You Would Like
Bolt should have an inventory plugin that gets targets from a list of virtual machines and scale sets on an Azure account. 

Users should be able to filter VMs and scale sets based on the following:

- Resource group
- Scale set
- Location
- Tags

The `name` and `uri` for a target should be set to the FQDN and public IP address, if available.

```
targets:
   - _plugin: azure
     location: eastus
     resource-group: my-group
     scale-set: my-set
     tags:
        key: value
```

It should be possible to set configuration for authorizing with Azure in the following locations:

- inventory config
- Bolt config
- environment variables (e.g. `ENV['AZURE_CLIENT_ID']`)
- a credentials file at `~/.azure/credentials`

```
plugins:
   azure:
      tenant-id: xxxx-xxxx
      client-id: xxxx-xxxx
      client-secret: xxxx-xxxx
      subscription-id: xxxx-xxxx
```

## Questions

- Should the `name` and `uri` always be set to the IP address / FQDN by default, or can these be overridden? This can be tricky since values in Azure's REST API are nested and might be difficult for the user to specify. Is there a need to specify other properties?
- Should VMs and scale sets be targeted separately? The above inventory config would load all VMs and scale sets that match the filters.
- If a credentials file is desired, should it be a `.ini` file? This is the format that the Azure SDKs use.
