### ISSUE TITLE
Configuration option(s) pointing to files do not expand `~`

### ISSUE THREAD

**Issue by donoghuc** [puppetlabs/bolt#1174]
## Describe the Bug
When the `token-file` for pcp/puppet-db is something like `~/.puppetlabs/token`, the home directory is not expanded. This can manifest in `file not found` errors. 

## Expected Behavior
The following config should work without needing fully qualified paths.
```
puppetdb:
  server_urls: ["https://master:8081"]
  cacert: "~/.puppetlabs/client-tools/ca.pem"
  token: "~/.puppetlabs/token"
pcp:
  service-url: "https://master:8143"
  cacert: "~/.puppetlabs/client-tools/ca.pem"
  token-file: "~/.puppetlabs/token"
  task-environment: dev
```
Instead (currently) the following error will occur:
```
% bolt task run service action=status name=puppet --transport pcp -t foo
Started on foo...
Failed on foo:
  token-file '~/.puppetlabs/token' is unreadable
Failed on 1 node: foo
Ran on 1 node in 0.18 seconds
```
