### ISSUE TITLE
Run apply_prep task with configured run_as

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#1191]
## Use Case
Users should be able to run the `puppet_agent::install` task as root during apply_prep

## Describe the Solution You Would Like
Should this be a new parameter to the `puppet-library -> plugin` config? A metaparameter to the task?

Proposed in #1123 
```
plugin_hooks:
  puppet_library:
    plugin: task
    task: 'bootstrap'
    _run_as: root
    parameters:
      master: 'puppet.example.com'
      cacert_content: <cert>
```

## Specifics

* If the transport does not support `_run_as` apply_prep should error.
