### ISSUE TITLE
Regex matches files in root folder

### ISSUE THREAD

**Issue by ksagle77** [puppetlabs/bolt#1276]
## Describe the Bug
When using inventory2 and searching using regex, filenames in the puppet_dir are matched and returned as target.

## Expected Behavior
Arbitrary filenames in the root folder shouldn't be search. Regex should match only against items in the specific inventory file.

## Steps to Reproduce
1. In $puppet_dir, create the following inventory.yaml:
```
version: 2
groups:
  - name: test_servers
    targets:
      - name: mytestserver01
        uri: mytestserver01.domain.name
```

2. Create an empty file called randomtestfile.txt in $puppet_dir

3. Run bolt inventory show --nodes *test*

```
     PS D:\dev\puppet_local> bolt inventory show --nodes *test*
     randomtestfile.txt
     1 target
```
Testfile is matched and returned as the target.

4. Delete randomtestfile.txt and run the same command.
```
    PS D:\dev\puppet_local> Remove-Item .\randomtestfile.txt
    PS D:\dev\puppet_local> bolt inventory show --nodes *test*
    mytestserver01
    1 target
    PS D:\dev\puppet_local> 
```

## Environment
 - Version 1.13.1
 - Windows 10
