### ISSUE TITLE
Standardize templated data in target plugins

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1325]
## Use Case
The Target plugins are kind of confusing because they contain templated data intermixed with options for the plugin.

* Users don't understand what options are template options vs other plugin options
* Users try to use static values in templated object
* Users try to use dynamic options outside the plugin(bad examples?)
* plugins in templates are not evaluated in the expected order.

## Solution
This code should live in a new 'plugin_helper' module. 

We should add a `target_mapping` key at the same level as `_plugin`, under which dynamic `name`, `uri`,  `config` etc. keys are nested.
```
groups:
  - name: cloud-webs
    targets:
      - _plugin: terraform
        dir: /path/to/terraform/project1
        resource_type: google_compute_instance.web
        target_mapping:
          uri: network_interface.0.access_config.0.nat_ip
          config:
            ssh:
              user: path.to.user
    config:
      ssh:
        password: static
        user:
        _plugin: prompt
        message: "Enter user:"
```
## Questions
- Should we allow static data in the `mappings` key? No, values under `mapping` can only be loaded dynamically from the plugin
- Should we use dot indexing? Not for keys, but we should support it for values (ie the TF plugin).
  - Don't need to worry about escaping dots for this.
  - When parsing dot-indexed values, the helper should treat numbers as indices if the object is an array, otherwise it should treat them as an integer.
