### ISSUE TITLE
`Alias` key in `bolt inventory show --detail` only shows alias from rightmost target definition

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#1379]
## Describe the Bug
If a target is defined multiple times with different aliases in an inventoryfile, the aliases are merged and the target can be run using any alias (https://github.com/puppetlabs/bolt/blob/master/lib/bolt/inventory/group2.rb#L416). However when printing the target, regardless of which alias is used, only the alias defined in the rightmost definition will be printed.

```yaml
---
version: 2
groups:
  - name: foo 
    targets:
      - name: localhost
        alias:
          - printed
          - boop
  - name: bar 
    targets:
      - name: localhost
        alias: also_printed
```

## Expected Behavior
The `--detail` output should list aliases from all groups a target is a member of.

## Steps to Reproduce
For example with this inventory, `bolt inventory show --detail` will output the same result for `-n all`, `-n localhost`, `-n printed`, `-n boop`, and `-n also_printed`, which is:

```
  "targets": [
    {
      "name": "localhost",
      "uri": null,
      "alias": "also_printed",
...
```
