### ISSUE TITLE
Plugins using dot syntax can't populate templated data with an array

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#1387]
## Describe the Bug
When using plugins that uses dot syntax to traverse data structures (only the Terraform plugin), if the expected return value is an array then an array of `nil` values will be returned from the plugin. 

## Expected Behavior
The templated value should be populated with the array value from the plugin.

## Steps to Reproduce
Using this inventory:
```yaml
  - name: tf
    config:
      ssh:
        run-as: root
    targets:
      - _plugin: terraform
        dir: ../terraform-playground/aws
        resource_type: aws_instance.*
        uri: public_ip
        name: public_dns
        config:
          ssh:
            run-as-command: security_groups
```
With a valid terraform environment, and using pry at line https://github.com/puppetlabs/bolt/blob/master/lib/bolt/transport/sudoable.rb#L10 to see what `run-as-command` is getting set to, I see that `run-as-command` is `[nil]` even when the value of `security_groups` in the tfstate file is `['allow-all']`

## Additional Context
We also need to make sure the case where the user provides an array of templated lookups behaves correctly, so:
```
  - name: tf
    config:
      ssh:
        run-as: root
    targets:
      - _plugin: terraform
        dir: ../terraform-playground/aws
        resource_type: aws_instance.*
        uri: public_ip
        name: public_dns
        config:
          ssh:
            run-as-command:
              - look.up
              - look.down
```
should also populate `look.up` and `look.down` appropriately

## Solution
We should use the postwalk_vals method instead https://github.com/puppetlabs/bolt/blob/master/lib/bolt/util.rb#L153
