### ISSUE TITLE
eyaml embedded in inventory.yaml generates errors causing bolt to fail

### ISSUE THREAD

**Issue by stowill** [puppetlabs/bolt#1451]
## Describe the Bug
The new features in Bolt [1.24.0](https://puppet.com/docs/bolt/latest/bolt_new_features.html#adds-support-for-embedding-eyaml-data-in-the-inventory-(1.24.0)) state `"adds support for embedding eyaml data in the inventory"` and refer to [BOLT-1270](https://tickets.puppetlabs.com/browse/BOLT-1270). There is also a mention in [BOLT-1257](https://tickets.puppetlabs.com/browse/BOLT-1257?focusedCommentId=667557&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-667557). The link about the plugin appears to have been moved to [here](https://puppet.com/docs/bolt/latest/using_plugins.html#ariaid-title15).

After working through the inaccuracies in the documentation and using **bolt secret encrypt 'password'** to generate the eyaml string, when attempting to run **bolt run command 'hostname'** an error is produced which differs depending on the version of the inventory file and if the target is Unix (ssh) or Windows (WinRM).

## Expected Behavior
Using an inventory file with a clear text password
```yaml
nodes:
  - name: windows-server.some.domain
    config:
      transport: winrm
      winrm:
        user: some_user
        password: somepassword
        ssl: true
```
You get output as follows:
```bash
[root@puppet-master bolt]# bolt command run 'hostname' --nodes windows-server.some.domain --no-ssl-verify
Started on windows-server.some.domain...
Finished on windows-server.some.domain:
  STDOUT:
    windows-server
Successful on 1 node: windows-server.some.domain
Ran on 1 node in 0.63 seconds
[root@puppet-master bolt]#
```

#### Version 1 inventory file connecting to a Unix host over ssh
```yaml
nodes:
  - name: linux-server.some.domain
    config:
      ssh:
        host-key-check: false
        user: some_user
        password:
          _plugin: pkcs7
          encrypted_value: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAftMW9yHKKer+C2m/qX/azGVsbLqH4mk6EF+t7OPW72dCpwVbhTviXJk9oDM61LcAYbKSExkkvHM3NiDBAr4JTURdpcZ2Ak9oLnpRpi6TFSCgAnRACO4G4Ls+LLnBrvjwixcbofq8dF4UZqyGy1wFPnplSBqzaBxfJK3w9LJ77CmQTfQbJD7EZgA8AWvNI6RPUvAN0Av5RV0kTh/wDnI8f6ez/r0gTQHqRPHRW4FUf15/UwwQ0w9gxJVxPCKYyMJGzsaRb+HUQ6meeW1l0Vp5/8GDDWi5hyybN9YuE5sUtzzDq3uw9wKewA8urbW/vkphenqMwSTZHtPe/b2OQl/bwjA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB4Sn0yLuD+FU04HwcpUxzpgBCONFwuUbSS01hD/1f1gEpJ]
        run-as: root
        sudo-password: somepassword
```
Running bolt produces the following output
```bash
[root@puppet-master bolt]# bolt command run 'hostname' --nodes linux-server.some.domain
Started on linux-server.some.domain...
Failed on linux-server.some.domain:
  Failed to connect to linux-server.some.domain: don't know how to write {"_plugin"=>"pkcs7", "encrypted_value"=>"ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAftMW9yHKKer+C2m/qX/azGVsbLqH4mk6EF+t7OPW72dCpwVbhTviXJk9oDM61LcAYbKSExkkvHM3NiDBAr4JTURdpcZ2Ak9oLnpRpi6TFSCgAnRACO4G4Ls+LLnBrvjwixcbofq8dF4UZqyGy1wFPnplSBqzaBxfJK3w9LJ77CmQTfQbJD7EZgA8AWvNI6RPUvAN0Av5RV0kTh/wDnI8f6ez/r0gTQHqRPHRW4FUf15/UwwQ0w9gxJVxPCKYyMJGzsaRb+HUQ6meeW1l0Vp5/8GDDWi5hyybN9YuE5sUtzzDq3uw9wKewA8urbW/vkphenqMwSTZHtPe/b2OQl/bwjA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB4Sn0yLuD+FU04HwcpUxzpgBCONFwuUbSS01hD/1f1gEpJ]"}
Failed on 1 node: linux-server.some.domain
[root@puppet-master bolt]#
```

#### Version 2 inventory file connecting to a Unix host over ssh
```yaml
version: 2
targets:
  - linux-server.some.domain
config:
  ssh:
    host-key-check: false
    user: some_user
    password:
      _plugin: pkcs7
      encrypted_value: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAftMW9yHKKer+C2m/qX/azGVsbLqH4mk6EF+t7OPW72dCpwVbhTviXJk9oDM61LcAYbKSExkkvHM3NiDBAr4JTURdpcZ2Ak9oLnpRpi6TFSCgAnRACO4G4Ls+LLnBrvjwixcbofq8dF4UZqyGy1wFPnplSBqzaBxfJK3w9LJ77CmQTfQbJD7EZgA8AWvNI6RPUvAN0Av5RV0kTh/wDnI8f6ez/r0gTQHqRPHRW4FUf15/UwwQ0w9gxJVxPCKYyMJGzsaRb+HUQ6meeW1l0Vp5/8GDDWi5hyybN9YuE5sUtzzDq3uw9wKewA8urbW/vkphenqMwSTZHtPe/b2OQl/bwjA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB4Sn0yLuD+FU04HwcpUxzpgBCONFwuUbSS01hD/1f1gEpJ]
    run-as: root
    sudo-password: somepassword
```
Running bolt produces the following output
```bash
[root@puppet-master bolt]# bolt command run 'hostname' --nodes linux-server.some.domain
Could not parse as an encrypted value:
[root@puppet-master bolt]#
```

#### Version 1 inventory file connecting to a Windows host over WinRM
```yaml
nodes:
  - name: windows-server.some.domain
    config:
      transport: winrm
      winrm:
        user: some_user
        password:
          _plugin: pkcs7
          encrypted_value: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAftMW9yHKKer+C2m/qX/azGVsbLqH4mk6EF+t7OPW72dCpwVbhTviXJk9oDM61LcAYbKSExkkvHM3NiDBAr4JTURdpcZ2Ak9oLnpRpi6TFSCgAnRACO4G4Ls+LLnBrvjwixcbofq8dF4UZqyGy1wFPnplSBqzaBxfJK3w9LJ77CmQTfQbJD7EZgA8AWvNI6RPUvAN0Av5RV0kTh/wDnI8f6ez/r0gTQHqRPHRW4FUf15/UwwQ0w9gxJVxPCKYyMJGzsaRb+HUQ6meeW1l0Vp5/8GDDWi5hyybN9YuE5sUtzzDq3uw9wKewA8urbW/vkphenqMwSTZHtPe/b2OQl/bwjA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB4Sn0yLuD+FU04HwcpUxzpgBCONFwuUbSS01hD/1f1gEpJ]
        ssl: true
```
Running bolt produces the following output
```bash
[root@puppet-master bolt]# bolt command run 'hostname' --nodes windows-server.some.domain --no-ssl-verify
Started on windows-server.some.domain...
Failed on windows-server.some.domain:
  Failed to connect to https://windows-server.some.domain:5986/wsman: undefined method `force_encoding' for #<Hash:0x0000000004399910>
Failed on 1 node: windows-server.some.domain
Ran on 1 node in 0.16 seconds
[root@puppet-master bolt]#
```

#### Version 2 inventory file connecting to a Windows host over WinRM
```yaml
version: 2
targets:
  - windows-server.some.domain
config:
  transport: winrm
  winrm:
    user: some_user
    password:
      _plugin: pkcs7
      encrypted_value: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAftMW9yHKKer+C2m/qX/azGVsbLqH4mk6EF+t7OPW72dCpwVbhTviXJk9oDM61LcAYbKSExkkvHM3NiDBAr4JTURdpcZ2Ak9oLnpRpi6TFSCgAnRACO4G4Ls+LLnBrvjwixcbofq8dF4UZqyGy1wFPnplSBqzaBxfJK3w9LJ77CmQTfQbJD7EZgA8AWvNI6RPUvAN0Av5RV0kTh/wDnI8f6ez/r0gTQHqRPHRW4FUf15/UwwQ0w9gxJVxPCKYyMJGzsaRb+HUQ6meeW1l0Vp5/8GDDWi5hyybN9YuE5sUtzzDq3uw9wKewA8urbW/vkphenqMwSTZHtPe/b2OQl/bwjA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB4Sn0yLuD+FU04HwcpUxzpgBCONFwuUbSS01hD/1f1gEpJ]
    ssl: true
```
Running bolt produces the following output
```bash
[root@puppet-master bolt]# bolt command run 'hostname' --nodes windows-server.some.domain --no-ssl-verify
Could not parse as an encrypted value:
[root@puppet-master bolt]#
```

## The format of encryption string doesn't matter

It doesn't matter what format is used for the encryption string in the inventory file. 
Storing it as a multi-line string gives the same results
```yaml
version: 2
targets:
  - windows-server.some.domain
config:
  transport: winrm
  winrm:
    user: some_user
    password:
      _plugin: pkcs7
      encrypted_value: >
        ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEw
        DQYJKoZIhvcNAQEBBQAEggEAftMW9yHKKer+C2m/qX/azGVsbLqH4mk6EF+t
        7OPW72dCpwVbhTviXJk9oDM61LcAYbKSExkkvHM3NiDBAr4JTURdpcZ2Ak9o
        LnpRpi6TFSCgAnRACO4G4Ls+LLnBrvjwixcbofq8dF4UZqyGy1wFPnplSBqz
        aBxfJK3w9LJ77CmQTfQbJD7EZgA8AWvNI6RPUvAN0Av5RV0kTh/wDnI8f6ez
        /r0gTQHqRPHRW4FUf15/UwwQ0w9gxJVxPCKYyMJGzsaRb+HUQ6meeW1l0Vp5
        /8GDDWi5hyybN9YuE5sUtzzDq3uw9wKewA8urbW/vkphenqMwSTZHtPe/b2O
        Ql/bwjA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB4Sn0yLuD+FU04Hwcp
        UxzpgBCONFwuUbSS01hD/1f1gEpJ]
    ssl: true
```
or
```yaml
version: 2
targets:
  - windows-server.some.domain
config:
  transport: winrm
  winrm:
    user: some_user
    password:
      _plugin: pkcs7
      encrypted_value: |
        ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEw
        DQYJKoZIhvcNAQEBBQAEggEAftMW9yHKKer+C2m/qX/azGVsbLqH4mk6EF+t
        7OPW72dCpwVbhTviXJk9oDM61LcAYbKSExkkvHM3NiDBAr4JTURdpcZ2Ak9o
        LnpRpi6TFSCgAnRACO4G4Ls+LLnBrvjwixcbofq8dF4UZqyGy1wFPnplSBqz
        aBxfJK3w9LJ77CmQTfQbJD7EZgA8AWvNI6RPUvAN0Av5RV0kTh/wDnI8f6ez
        /r0gTQHqRPHRW4FUf15/UwwQ0w9gxJVxPCKYyMJGzsaRb+HUQ6meeW1l0Vp5
        /8GDDWi5hyybN9YuE5sUtzzDq3uw9wKewA8urbW/vkphenqMwSTZHtPe/b2O
        Ql/bwjA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB4Sn0yLuD+FU04Hwcp
        UxzpgBCONFwuUbSS01hD/1f1gEpJ]
    ssl: true
```
give the same failure messages

## Environment
 - Version [Bolt 1.29.1]
 - Platform [CentOS Linux 7 (Core)]

Hopefully the issue is just an error in documentation and lack of complete examples rather than an actual bug.
