### ISSUE TITLE
Command audit list

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/bolt#1510]
## Use Case
In a high security environment in order to use ssh/sudo I must provide a list of all the commands I will run with privilege access so that the security team can grant my user access to the commands ahead of time before I can gain access to the system(s). This is often detailed in a remedy change request ticket.  It would be helpful if I can have bolt generate a list of commands it will run with a specified task or plan. 

## Describe the Solution You Would Like
I would like to see something like the following command:

Example:

```
# bolt.yaml
ssh:
  tmpdir: '/home/bolt-svc/tmp/'
  script-dir: 'bolt-scripts'

bolt task run puppet_agent::install --audit-only

Commands run during task:

- /usr/bin/mkdir -m 0700 /home/bolt-svc/tmp/bolt-scripts
- /usr/bin/chown +x /home/bolt-svc/tmp/bolt-scripts/puppet_agent_install.rb
- /usr/bin/ruby /home/bolt-svc/tmp/bolt-scripts/puppet_agent_install.rb
- /usr/bin/rm -rf /home/bolt-svc/tmp/bolt-scripts/
```

## Describe Alternatives You've Considered
`bolt task run puppet_agent::install  --debug |grep /`

Grepping for things that look like commands in the debug output.
