### ISSUE TITLE
Support multiple PuppetDB connections in inventory.yaml

### ISSUE THREAD

**Issue by tspeigner** [puppetlabs/bolt#1527]
## Use Case
Currently you can only define the puppetdb connection information in the bolt.yaml configuration.  It is currently designed to only allow one db configuration.  It would be nice if it could be added to the inventory file as part of the config for the plugin on targets.

## Describe the Solution You Would Like
Something like this in the inventory file:

`version: 2

groups:

  - name: cluster1

    targets:

      - _plugin: puppetdb

        query: "inventory[certname] {}"

    config:

      puppetdb:

        server_urls: ["https://cluster1.domain:8081"]

        cacert: /home/user/.puppetlabs/cluster1.ca.crt

        token: /home/user/.puppetlabs/cluster1.token

      transport: pcp

      pcp:

        service-url: "https://cluster1.domain:8143"

        cacert: /home/user/.puppetlabs/cluster1.ca.crt

        token-file: /home/user/.puppetlabs/cluster1.token

  - name: cluster2

    targets:

      - _plugin: puppetdb

        query: "inventory[certname] {}"

    config:

      puppetdb:

        server_urls: ["https://cluster2.domain:8081"]

        cacert: /home/user/.puppetlabs/cluster2.ca.crt

        token: /home/user/.puppetlabs/cluster2.token

      transport: pcp

      pcp:

        service-url: "https://cluster2.domain:8143"

        cacert: /home/user/.puppetlabs/cluster2.ca.crt

        token-file: /home/user/.puppetlabs/cluster2.token`

**Comment by adreyer** [comment]
This won't work well because the puppetdb instance is configured on the group and won't be available to the plugin. Further while it could be used by the `facts` plan and during apply it would not "just work" for most uses of the `pdb_query` function or `--query`

I can see two ways to implement this:
1. Support it just for populating groups by making it an argument to the plugin.
ie
```
version: 2
groups:
  - name: cluster1
    targets:
      - _plugin: puppetdb
        query: "inventory[certname] {}"
        connection:
          server_urls: ["https://cluster1.domain:8081"]
          cacert: /home/user/.puppetlabs/cluster1.ca.crt
          token: /home/user/.puppetlabs/cluster1.token
      transport: pcp
      pcp:
        service-url: "https://cluster1.domain:8143"
        cacert: /home/user/.puppetlabs/cluster1.ca.crt
        token-file: /home/user/.puppetlabs/cluster1.token
```

2. Update the pdb client to be federation aware and configure multiple instances in `bolt.yaml` which are then referenced in the inventory.

```
version: 2
groups:
  - name: cluster1
    targets:
      - _plugin: puppetdb
        query: "inventory[certname] {}"
        instance: cluster1
      transport: pcp
      pcp:
        service-url: "https://cluster1.domain:8143"
        cacert: /home/user/.puppetlabs/cluster1.ca.crt
        token-file: /home/user/.puppetlabs/cluster1.token
```
