### ISSUE TITLE
Make it easier to test functions that use Plan Datatypes with rspec-puppet

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1688]
## Use Case
The Plan Datatypes live in the boltlib module that ships with the bolt gem which makes it hard to test functions that rely on them.

## Describe the Solution You Would Like

A helper from BoltSpec that can be used to wrap an rspec-puppet function test that creates the same context as a plan executor. You should be able to call the `allow_task` etc functions inside this wrapper.

## Describe Alternatives You've Considered
1. A BoltSpec function that returns the path to `bolt-modules` inside the gem.
2. CI that publishes bolt-modules to forge

These will not create an executor or inventory so most functions that use plan language features would still fail.

**Comment by logicminds** [comment]
For the time being I ended up mocking the TargetSpec type via `let(:pre_condition) { "type TargetSpec = Variant[String[1], Target, Array[TargetSpec]]" }` in the function spec file.

Or if using the debugger I can define the type via `type TargetSpec = Variant[String[1], Target, Array[TargetSpec]]`

Additionally, I also added these symlinks in my fixtures.  I don't know if any of these options are the best route but they do seem to solve some issues and create new ones too. 

```
symlinks:
    "peadm": "#{source_dir}"
    out: "#{source_dir}/.bundle/gems/bolt-1.49.0/bolt-modules/out"
    ctrl: "#{source_dir}/.bundle/gems/bolt-1.49.0/bolt-modules/ctrl"
    file: "#{source_dir}/.bundle/gems/bolt-1.49.0/bolt-modules/file"
    system: "#{source_dir}/.bundle/gems/bolt-1.49.0/bolt-modules/system"
    boltlib: "#{source_dir}/.bundle/gems/bolt-1.49.0/bolt-modules/boltlib"
```
