### ISSUE TITLE
Ability to add facts to nodes queried from PuppetDB

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#1690]
## Use Case
As a plan author i would like to utilize facts on nodes to classify them when performing work. Sometimes certain tasks need to be executed on nodes based on facts.

## Describe the Solution You Would Like
Having just worked a bit on the `puppetdb` plugin, i know we have the ability to gather specific facts for nodes. I'm thinking that we could offer a solution that would use this plugin to query PuppetDB and populate all facts on the targets it returns.

#### Ideas 1 - Having a flag to set all facts

Use a flag, i call it `assign_facts_from_puppetdb` that will tell the plugin to query PuppetDB for all facts on each node returned in `query`, then set all of those facts on the targets returned from the plugin.

```yaml
  - name: puppetdb_windows
    targets:
      - _plugin: puppetdb
        query: "inventory[certname] { facts.osfamily = 'windows' }"
        assign_facts_from_puppetdb: true
```

#### Ideas 2 - Have a "special" variable that can be used in `target_mapping`

Create a "special" variable to be used in `target_mapping` that maps to "all the facts".
Users can then assign this to the `facts` hash in the `target_mapping`, basically telling the plugin to query for "all the facts" from PuppetDB and assign them to the facts on the returned targets.

```yaml
  - name: puppetdb_windows
    targets:
      - _plugin: puppetdb
        query: "inventory[certname] { facts.osfamily = 'windows' }"
        target_mapping:
          facts: all_facts
```

## Additional Context
As of this PR https://github.com/puppetlabs/bolt/pull/1689 we can already set explicit facts, but makes it tedious to specify _all_ the facts in the database.

```yaml
  - name: puppetdb_windows
    targets:
      - _plugin: puppetdb
        query: "inventory[certname] { facts.osfamily = 'windows' }"
        target_mapping:
          facts:
            puppetversion: facts.puppetversion
```
