### ISSUE TITLE
Allow plugins to resolve keys in puppetdb config

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#1771]
## Use Case
I'm trying to write a plugin that can resolve certificates for the PuppetDB plugin. This way we can support different laptop setups along with automatically generating the cert name given the hostname of the bolt control node (because the certs are usually: `/etc/puppetlabs/puppet/ssl/certs/<fqdn>.pem`).

## Describe the Solution You Would Like
Ability to do the following:
```
puppetdb:
  server_urls: ["https://puppetdb.domain.tld:8081"]
  cacert:
    _plugin: task
    task: inventory_utils::path_lookup
    parameters:
      paths:
        - ~/.puppetlabs/bolt/customer/ssl/certs/ca.pem
        - /etc/puppetlabs/puppet/ssl/certs/customer/ca.pem
        - /etc/puppetlabs/puppet/ssl/certs/ca.pem
  cert:
    _plugin: task
    task: inventory_utils::path_lookup
    parameters:
      paths:
        - ~/.puppetlabs/bolt/customer/ssl/certs/bolt.pem
        - /etc/puppetlabs/puppet/ssl/certs/customer/bolt.pem
        - /etc/puppetlabs/puppet/ssl/certs/bolt.pem
        - _plugin: task
          task: inventory_utils::erb_template
          parameters:
            template: '/etc/puppetlabs/puppet/ssl/certs/<%= Socket.gethostname %>.pem'
```

## Current behavior
When i try do that current i get the following:
```
Found unsupported key _plugin in config setting puppetdb. Plugins are only available in ssh, winrm, pcp, local, docker, remote, plugins, plugin_hooks.  
```
