### ISSUE TITLE
Plans error on apply when targets share identical config

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#1836]
## Describe the Bug
When calling `apply` on multiple targets that share identical configuration, the plan will fail with an obscure error:

```
Apply failed to compile for TARGET: undefined method `[]' for #<Bolt::ApplyTarget:0x000000000297cfa0> on node TARGET
```

This is caused by an update to the applicator that sets `local_references: true` when serializing targets. When target objects are serialized, any targets that have similar config to another target will receive references to that config. For example, target B shares similar ssh cofiguration to target A:

```
targets:
  - name: targetA
    config:
      ssh:
        host-key-check: false
        run-as: root
        tty: true
  - name: targetB
    config:
      ssh:
        host-key-check: false
        run-as: root
        tty: true
```

When the targets are serialized, target B will receive a reference to target A's ssh configuration, resulting in a catalog that looks like this for target B:

```
...
"mygroup"=>	
  [{"__ptype"=>"Target",	
    "name"=>"targetB",	
    "config"=>{"transport"=>"ssh", "ssh"=>{"__ptype"=>"LocalRef", "__pvalue"=>"$['targetA'][0]['config']['ssh']"}},
...
```

When this is deserialized, Puppet will see the reference to target A, which has already been deserialized and is now an `ApplyTarget` object, and attempt to access its config with the `[]` method, causing the plan to fail.

## Expected Behavior
Targets should be deserialized without raising errors, even if they share similar config.

## Possible Solutions
- Have Bolt deserialize itself?
- Have Bolt replace references prior to deserialization?
- Update Puppet to not access the deserialized object and use the data hash instead?
- Something else?
