### ISSUE TITLE
Parsing default plan values is strange

### ISSUE THREAD

**Issue by donoghuc** [puppetlabs/bolt#1854]
## Describe the Bug
There is some strangeness how puppet-strings/YARD parses default plan parameters. The following plan shows some of the discrepensies:
```puppet
plan test::parsing(
	$bare = bare,
	$single = 'single',
	$double = "double",
	$arithmetic = 1 + 1,
	$code = Target.new('foo')
){}
```
```
cas@cas-ThinkPad-T460p:~/working_dir/bolt$ bolt plan show test::parsing

test::parsing

USAGE:
bolt plan run test::parsing [bare=<value>] [single=<value>] [double=<value>] [arithmetic=<value>] [code=<value>]

PARAMETERS:
- bare: Any
    Default: bare
- single: Any
    Default: 'single'
- double: Any
    Default: "double"
- arithmetic: Any
    Default: +
- code: Any
    Default: ('foo')

MODULE:
/home/cas/working_dir/bolt/Boltdir/site/test
```
## Expected Behavior
Some of those appear to be bugs, Others (like the quoting of strings) is maybe right? Either way it appears to be kind of strange. 

## Additional context
We are looking at displaying default values in the PE console.
