### ISSUE TITLE
Facts from PuppetDB inventory plugin appear to always be strings

### ISSUE THREAD

**Issue by tdb** [puppetlabs/bolt#1897]
## Describe the Bug
Facts returned from the PuppetDB inventory plugin appear to always be strings. This makes them fail for values that are not strings. Eg:

`port must be a Integer, received String "2222"`

The value appears to be an Integer value in PuppetDB.

## Expected Behavior
Either it uses the correct type, or have some mechanism to cast it to the correct type in the inventory file.

## Steps to Reproduce
Create an inventory file using the PuppetDB inventory plugin with a section like this:

```
- name: debian
  targets:
    _plugin: puppetdb
    query: "inventory[certname] { facts.operatingsystem = 'Debian' }"
    target_mapping:
      config:
        ssh:
          port: facts.sshd_port
```

## Environment
Bolt version 2.13.0 on Ubuntu 16.04.

## Additional Context
sshd ports are not the same across our hosts, so it needs to be gathered from PuppetDB.
