### ISSUE TITLE
JSON schemas flag plugin references as invalid

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#1900]
## Describe the Bug
Many of the options that can be set in `bolt.yaml`, `bolt-project.yaml`, and `inventory.yaml` expect a non-hash value but accept a plugin reference that will be resolved by Bolt and (hopefully) return a value with the expected type. The JSON schema correctly validates options based on their values' expected types, but does not support adding plugin references for options that accept them and will mark these plugin references as invalid.

## Expected Behavior
The JSON schemas should support having a plugin reference anywhere they are supported and not flag the plugin reference as invalid.

## Steps to Reproduce
1. Enable support for the schemas in VS Code
2. Create an inventoryfile with the following:
   ```yaml
   ssh:
     config:
       password:
         _plugin: vault
        path: secrets/bolt
        field: bolt-password
   ```

VS Code will highlight `_plugin` as invalid and display the error `Incorrect type. Expected "string".`

## Questions

- Can we generate these instead of hard-coding them?
