### ISSUE TITLE
Add a function to generate content from a template

### ISSUE THREAD

**Issue by kreeuwijk** [puppetlabs/bolt#1910]
## Use Case
In Plans, I sometimes need to generate some content. If the content is dynamic, this is easiest with Puppet's builtin templating functions (`template()`, `epp()`). But in Bolt I would have to use an `apply()` block to have access to the function, and write the file out to disk to get back to it in the plan. That's not very efficient.

## Describe the Solution You Would Like
It would be better if Bolt had it's own function to generate content from a template directly, e.g. `generate::template()`
An example would look like this (template at `example/templates/my_file.epp`):
`$content = generate::template('example/my_file.epp', { 'github_user' => $github_usr })`

## Describe Alternatives You've Considered
See an example of how this requires an apply() block today [here](https://github.com/puppetlabs-seteam/workshop_deploy/blob/master/plans/hydra.pp#L35-L41)

**Comment by nicklewis** [comment]
The built-in templating functions should work fine outside an `apply()` block. It seems to work in my local testing... Is there a specific case where it doesn't do what you need?

**Comment by kreeuwijk** [comment]
You're absolutely right, closing this issue!

**Comment by jkkitakita** [comment]
I also worked fine inside `apply()`.
The target is localhost.

## Spec

- OS: MacOS
- bolt version: 2.30.0

## Example

### pp

```puppet
apply($master) {
  file { '/root/prep.ps1':
    ensure  => file,
    content => epp('workshop_deploy/prep_ps1.epp', {
      'github_user' => "${github_user}",
    }),
  }
}
```

### yaml

```yaml
- name: github_user
  targets: $master
  resources:
    - type: file
      title: '/root/prep.ps1'
      parameters:
        ensure: file
        content: |
          epp('workshop_deploy/prep_ps1.epp', {
            'github_user' => "${github_user}",
          })
```
