### ISSUE TITLE
SSH Config breaks bolt despite native-ssh transport

### ISSUE THREAD

**Issue by fuero** [puppetlabs/bolt#2289]
## Describe the Bug

A valid ssh client config breaks bolt's ssh transport in native-ssh mode, even with `load-config: false`.

## Expected Behavior

Bolt running ssh as is and leaving the client config alone

## Steps to Reproduce

1. Have an SSH config with a `Match host canonical all` block
2. Set up bolt with this config:

```yaml
config:
  ssh:
    ssh-command: 'ssh'
    native-ssh: true
    load-config: false
    user: root
    host-key-check: false
```

3. Run the `facts` plan on all hosts:

```
$ bolt plan run facts targets=all
Starting: plan facts
Starting: task facts on hosta
Finished: task facts with 1 failure in 0.06 sec
Finished: plan facts in 0.07 sec
Failed on shibboleth:
  all cannot be mixed with other conditions
Failed on 1 target: hosta
Ran on 1 target
```

## Environment

 - Bolt version 2.32.0
 - OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020
 - Arch Linux

**Comment by lucywyman** [comment]
Using `all` to match hosts [isn't supported by our underlying SSH library](https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/config.rb#L366), and I think it'd be a relatively big effort to add support for it. You should be able to do something like:
```
CanonicalizeHostname yes
Host *.mydomain.com
    User myusername
```

Does that work for your use case?

**Comment by fuero** [comment]
@lucywyman 
I was under the impression that using native ssh would disable net-ssh. As this obviously doesn't, why doesn't `load-config: false` make bolt (or rather net-ssh) ignore my ssh client config as suggested by the documentation?

Adjusting my SSH config to a tool's shortcomings isn't helpful, especially as the software that mandates the config format (OpenSSH) parses it without issue.

**Comment by beechtom** [comment]
@fuero Can you share the directory structure for your project and the full contents of `inventory.yaml`? You're correct that setting `native-ssh: true` should disable net-ssh, and that `load-config: false` should ignore SSH config when using net-ssh.

**Comment by fuero** [comment]
It's pretty much the demo project, here's the inventory.yaml file:
```yaml
config:
  ssh:
    ssh-command: 'ssh'
    native-ssh: true
    load-config: false
    user: root
    host-key-check: false
groups:
  - name: boxes
    targets:
      - hosta
      - hostb
```
