### ISSUE TITLE
Raise plan error when YAML plan has an empty step

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2309]
## Describe the Bug
The following plan should raise a helpful error message

```
parameters:
  targets:
    type: TargetSpec
    description: A list of targets to run actions on
    default: localhost

steps:
  -
  - message: Hello from bolt::bug
```
(Output comes from yaml_plan.rb#L50)

We should raise an error for anything that isn't a valid step (ie the actual object type is wrong - anything except for a hash with valid step keys). This validation should happen before execution.
