### ISSUE TITLE
Create an inventoryfile as part of bolt project init

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2364]
## Use Case
If an inventoryfile already exists, do nothing.
Proposed default content (all commented out). This should include top-level config as well, and includes updating the documentation to have the same example under 'basic example'
```
---
# This is an example inventory.yaml
# Link to docs
groups:
  - name: linux
    targets:
      - target1.example.com
      - target2.example.com
    config:
      transport: ssh
      ssh:
        user: myuser
  - name: windows
    targets:

      - uri: target4.example.com
        alias: windows2
    config:
      transport: winrm
```
Question:
- Should this accept an argument to configure adding to it? I can imagine taking a list of bare hostnames and adding them to a top-level `targets` key. _This is a little too complex and doesn't provide enough value to conside_.
