### ISSUE TITLE
Support YAML anchors in hiera.yaml

### ISSUE THREAD

**Issue by op-ct** [puppetlabs/bolt#2433]
## Use Case

Defining large lists in Hiera 5 hierarchies can become quite repetitive.  I would like to use YAML anchors to DRY them up.

## Describe the Solution You Would Like

Permit the use of YAML anchors in  `hiera.yaml`.  

Something like this:

```yaml
        ---
        version: 5

        defaults:
          datadir: "data"

        hierarchy:
          - name: "YAML backend"
            data_hash: yaml_data
            paths: &lookup_paths
              - "host/%{trusted.certname}.yaml"
              - "host/%{facts.networking.fqdn}.yaml"
              - "host/%{facts.networking.hostname}.yaml"
              - "domain/%{facts.networking.domain}.yaml"
              - "os/%{facts.os.name}/%{facts.os.release.full}.yaml"
              - "os/%{facts.os.name}/%{facts.os.release.major}.yaml"
              - "os/%{facts.os.name}.yaml"
              - "os/%{facts.os.family}.yaml"
              - "common.yaml"
          - name: "EYAML backend"
            lookup_key: eyaml_lookup_key
            paths: *lookup_paths
            options:
              pkcs7_private_key: path/to/private_key.pkcs7.pem
              pkcs7_public_key:  path/to/public_key.pkcs7.pem
```

Is preferable to something like this:

```yaml
        ---
        version: 5

        defaults:
          datadir: "data"

        hierarchy:
          - name: "YAML backend"
            data_hash: yaml_data
            paths:
              - "host/%{trusted.certname}.yaml"
              - "host/%{facts.networking.fqdn}.yaml"
              - "host/%{facts.networking.hostname}.yaml"
              - "domain/%{facts.networking.domain}.yaml"
              - "os/%{facts.os.name}/%{facts.os.release.full}.yaml"
              - "os/%{facts.os.name}/%{facts.os.release.major}.yaml"
              - "os/%{facts.os.name}.yaml"
              - "os/%{facts.os.family}.yaml"
              - "common.yaml"
          - name: "EYAML backend"
            lookup_key: eyaml_lookup_key
            paths:
              - "host/%{trusted.certname}.yaml"
              - "host/%{facts.networking.fqdn}.yaml"
              - "host/%{facts.networking.hostname}.yaml"
              - "domain/%{facts.networking.domain}.yaml"
              - "os/%{facts.os.name}/%{facts.os.release.full}.yaml"
              - "os/%{facts.os.name}/%{facts.os.release.major}.yaml"
              - "os/%{facts.os.name}.yaml"
              - "os/%{facts.os.family}.yaml"
              - "common.yaml"
            options:
              pkcs7_private_key: path/to/private_key.pkcs7.pem
              pkcs7_public_key:  path/to/public_key.pkcs7.pem
```

## Describe Alternatives You've Considered

The status quo.  It's irksome, but not fatal.

## Additional Context

`YAML.safe_load` disables aliases by default because of their potential to stage a DOS by way of a [YAML bomb](https://gist.github.com/superbrothers/d0c8d56e5797ea8fabcc3eb7984de52f).  However, in the case of a Bolt project's `hiera.yaml` file, such a problem would be self-inflicted and limited to the user's local execution environment.
