### ISSUE TITLE
Regression - No longer allowing plugins in puppetdb config

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#2461]
## Describe the Bug
Previously this issue https://github.com/puppetlabs/bolt/issues/1771 was fixed here https://github.com/puppetlabs/bolt/pull/1805

It appears that this is no longer working with the latest version of Bolt

## Steps to Reproduce
```yaml
$ bolt group show
Invalid configuration at /home/nmaludy/storage/home/src/encore/puppet-control-repo/bolt/bolt-project.yaml:
  Value at 'puppetdb.cacert' is a plugin reference, which is unsupported at this location
```

bolt-project.yaml
```yaml
puppetdb:
  server_urls: ["https://xxx:8081"]
  cacert:
    _plugin: task
    task: inventory_utils::pick_path
    parameters:
      paths:
        - /etc/puppetlabs/puppet/ssl/dev/certs/ca.pem
        - /etc/puppetlabs/puppet/ssl/certs/ca.pem
```

## Environment
 - Version 
```shell
$ bolt --version
2.37.0
```
 - Platform CentOS 7
