### ISSUE TITLE
Clarify using interpolations in plan_hierarchy

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#2467]
## Describe the Change You Would Like
Our documentation on `plan_hierarchy` in Hiera suggests that Hiera lookups outside of apply blocks do not support interpolations. However, Hiera lookups outside of apply blocks _do_ support interpolations, as long as the variable being interpolated is defined. We should clarify that outside of apply blocks, target-level data such as facts is not available, so interpolations that would normally work under `hierarchy` won't work under `plan_hierarchy` unless the variable being interpolated is explicitly defined.

## Example

Following is a basic example of interpolation with a plan variable under `plan_hierarchy`:

```yaml
# hiera.yaml
version: 5
defaults:
  datadir: data
  data_hash: yaml_data

plan_hierarchy:
  - name: "OS data"
    path: "%{os}.yaml"
  - name: "Common data"
    path: common.yaml
```

```yaml
# data/ubuntu.yaml
foo: ubuntu.yaml
```

```yaml
# data/common.yaml
foo: common.yaml
```

```puppet
# init.pp
plan bolt(String $os) {
  return lookup('foo')
}
```

```shell
$ bolt plan run bolt os=ubuntu                                                                                                      
Starting: plan bolt
Finished: plan bolt in 0.01 sec
"ubuntu.yaml"
```

```shell
$bolt plan run bolt os=windows
Starting: plan bolt
Finished: plan bolt in 0.01 sec
"common.yaml"
```

## TODO
Add philosophy around why this is undefined behavior (unlike how HIera is used elsewhere, incidental to using HIera, plan calling plan example). to this issue.
