### ISSUE TITLE
Unknown options warning messages with bolt 2.38.0

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#2477]
## Describe the Bug
When running Bolt `2.38.0` i'm seeing the following warning messages:

```
Unknown option 'version' at xxx/bolt/patching/inventory.yaml.
Unknown option 'port' at 'groups.0.config.remote' at xxx/bolt/patching/inventory.yaml.
Unknown option 'username' at 'groups.0.config.remote' at xxx/bolt/patching/inventory.yaml.
Unknown option 'password' at 'groups.0.config.remote' at xxx/bolt/patching/inventory.yaml.
```

## Expected Behavior
No warning messages shown.

## Steps to Reproduce
Here is my `inventory.yaml`
```yaml
---
version: 2
groups:
  - name: xxx
    config:
      transport: remote
      remote:
        port: 1234
        username: 'user@domain.tld'
        password: xxx
```

## Environment
 - Version `2.38.0`
