### ISSUE TITLE
Better error when trying to install a module from a private git repo

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2519]
## Describe the Bug
When trying to install a module from a private Git repo the resulting error is a bit misleading:

```
lucy ~/githubs/bolt/project ((eb3edb98...)) $ be bolt module install
Installing project modules

Missing metadata.json at https://github.com/puppetlabs/my-private-module. This is not a valid module.
```

We should check that the repo as a whole 404s to see if it's just missing metadata.json and if the whole repo 404s we can raise an error that says that the repo was not found and maybe private.

## Steps to Reproduce
```yaml
---
# bolt-project.yaml
name: project
modules:
  - git: https://github.com/puppetlabs/my-private-module
    ref: main
```

```
bolt module install
```
OR
```
Install-BoltModule
```
