### ISSUE TITLE
Bolt 3.0 slow down testing ticket

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2625]
## Describe the Bug
Please post any stats you're seeing, including any plans you're using that are slowed down in Bolt 3.0.

**Comment by adreyer** [comment]
problem can be replicated by the user with bolt apply and the following modules 

```
modules:
- name: puppetlabs/java
  version_requirement: 6.3.0
- name: saz/limits
  version_requirement: 3.0.4
- name: puppet/splunk
  version_requirement: 8.0.0
- name: puppetlabs/stdlib
  version_requirement: 6.5.0
- name: puppet/autofs
  version_requirement: 6.0.0
- name: puppetlabs/concat
  version_requirement: 6.2.0
- name: puppetlabs/host_core
  version_requirement: 1.0.3
- name: derdanne/nfs
  version_requirement: 2.1.6
```
