### ISSUE TITLE
Only execute prompt-plugin when necessary

### ISSUE THREAD

**Issue by fetzerms** [puppetlabs/bolt#2703]
## Use Case

I am currently building a dynamic inventory.yaml using a plugin. The plugin itself needs parameters, that are passed from the environment using the env_var plugin. In case the env-var is not set, I want to prompt the user for their input.

Example inventory.yaml:
```
groups:
  - name: test
    groups:
      - _plugin: test_inventory
        token:
          _plugin: "env_var"
          var: "API_TOKEN"
          defaut:
            _plugin: "prompt"
            message: "Enter your personal api token"
```

While this works, the user always gets asked for their api token, even when the env_var is set. I assume this is, because the possible default value gets evaluated first.

## Describe the Solution You Would Like

I want the prompt to only be shown then the actual default value needs to be read/retrieved.

## Describe Alternatives You've Considered

I can leave out the default value and let the run fail. The user will then know, that they need to specify the environmental variable.
