### ISSUE TITLE
bolt project migrate doesn't remove version from inventory.yaml

### ISSUE THREAD

**Issue by genebean** [puppetlabs/bolt#2745]
## Describe the Bug
Running `bolt project migrate` doesn't remove version from inventory.yaml which results in bolt still complaining about an unknown key named `version` in the inventory file.

## Expected Behavior
I expect the migrate command to deal with all things that are no longer valid.

## Steps to Reproduce
1. create `Boltdir/inventory.yaml` with this at the beginning:
   ```yaml
   ---
   version: 2
   config:
     ssh:
       host-key-check: false
   ```
2. run `bolt project migrate`
3. run `bolt plan run foo`
4. observe yellow output

## Environment
 - Version 3.4.0
 - Platform macOS 11.2.3 on Apple Silicon
