### ISSUE TITLE
Metaparameters for task step in yaml plans raise an error

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#2777]
## Describe the Bug
Trying to set a metaparameter in a yaml plan task step raises an error about

## Expected Behavior
The following should be a valid task step
```
steps:
  -
     name: command_step 
    task: service
    targets: $targets
    catch_errors: false
    parameters:
      action: status
      name: puppet
```

instead it fails with 
```
Parse error in step "command_step": 
 Cannot specify metaparameters when using top-level keys with same name: _catch_errors

```

### Environment
 - Version  3.5
