### ISSUE TITLE
Native SSH transport cannot connect with just a password

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2875]
## Describe the Bug
SSH doesn't support passing in a password to the command in a non-interactive way, so when users aren't able to set up SSH keys to connect to targets there's no way to connect using the native SSH transport.

[Relevant slack thread](https://puppetcommunity.slack.com/archives/C7GP57T50/p1623189559197400)

To support this, we should add a new `native-ssh` transport configuration option `enable-password-only` (bikeshed name) that will turn off `BatchMode` in the native-ssh transport. Once that's available, the following config should work for password-only SSH connections. We should document this, and clarify that it requires [sshpass](https://linux.die.net/man/1/sshpass) to be installed.
```
    config:
      transport: ssh 
      ssh:
       native-ssh: true
       ssh-command:
         - sshpass
         - -p
         - _plugin: prompt
           message: Enter your password
         - ssh
```
