### ISSUE TITLE
"bolt module install" no longer works when there's a task plugin in the bolt-project file

### ISSUE THREAD

**Issue by jschoewe** [puppetlabs/bolt#2992]
## Describe the Bug
When running "bolt module install" on a project, installing the modules from the Puppetfile needs to be the first thing that happens because tasks from those modules sometimes need to be used as plugins in the bolt-project.yaml file.

## Steps to Reproduce

Puppetfile:
```
mod 'puppetlabs-stdlib'
mod 'encore-inventory_utils'
```

bolt-project.yaml
```yaml
---
name: deploy

# paths are relative to this bolt.yaml file
hiera-config: "./hiera.yaml"
modulepath: "./modules_extern:./modules"

log:
  console:
    level: info

plugins:
  pkcs7:
    public_key:
      _plugin: task
      task: inventory_utils::pick_path
      parameters:
        paths:
          - ~/.ssh/public_key.pkcs7.pem
          - ~/.puppetlabs/bolt/keys/public_key.pkcs7.pem
    private_key:
      _plugin: task
      task: inventory_utils::pick_path
      parameters:
        paths:
          - ~/.ssh/private_key.pkcs7.pem
          - ~/.puppetlabs/bolt/keys/private_key.pkcs7.pem
```

Running "bolt module install" on a project with these files results in the following error:
```
Loaded project from '/path/to/project/deploy'
Could not find a task named 'inventory_utils::pick_path'. For a list of available tasks, run 'bolt task show'.
```

## Expected Behavior
Prior to version 3.16, these modules were being installed fine and we were able to use their tasks in the bolt-project file.

## Environment
RHEL 8
