### ISSUE TITLE
Unable to copy files when using gcloud compute scp

### ISSUE THREAD

**Issue by jaevans** [puppetlabs/bolt#3116]
## Describe the Bug
Based on the example in #3069 I am attempting to use the "native" `gcloud compute ssh` functionality. Command execution works following the example, but file copies fail as the username for the ssh connection is unknown by the host running bolt. This results in a destination of `@hostname:/dest/file/path` passed to `gcloud compute scp` resulting in an error message as `scp` sees this as a local file location.

## Expected Behavior
Files are copied to the remote computer.

## Steps to Reproduce
1. Create an inventory that references a GCP instance and set options to use `gcloud compute ssh`
```
config:
  transport: ssh
    ssh:
    native-ssh: true
    ssh-command: [gcloud, compute, ssh]
    copy-command: [gcloud, compute, scp, --recurse]
```
2. Run a plan containing `apply_prep($targets, '_run_as' => 'root')`

## Environment
 - Version 3.23.1
 - Platform Ubuntu Jammy (22.04) container host, Mac host
 - Centos 8 destination

## Additional Context

I'm running this in a docker container due to other problems I've had with bolt on my mac.
