### ISSUE TITLE
Remove restriction on characters that can appear in the group name atttribute.

### ISSUE THREAD

**Issue by PaulGale** [puppetlabs/bolt#3122]
If one has a `inventory.yaml` that looks like this:

```
groups:
  - name: ba
    groups:
      - name: ba.c1
        facts:
          cluster: 1
```

Then the Group's `name` attribute with the value `ba.c1` is reported by Bolt as an error as it contains the period character. 

Please remove all restrictions on the characters that can appear in the value of a  Group's `name` attribute consistent with the YAML standard.
