### ISSUE TITLE
Bolt puppetdb plugin example usage

### ISSUE THREAD

**Issue by pr3c0g** [puppetlabs/bolt#3172]
## Describe the Change You Would Like
The example usage section for the puppetdb plugin mentions `target_mapping` with both `alias` and `name`, but at least in my environment, this exact code will result in an error:

```yaml
targets:
  - _plugin: puppetdb
    query: "inventory[certname] { facts.osfamily = 'RedHat' }"
    target_mapping:
      alias: facts.hostname
      name: certname
```

Error:
```
Target test00-00.domain.com does not have a host
```

Changing the `target_mapping` above to have `uri` instead of `name` makes it work.
I'm not sure I understand the error message, but I wanted to leave my suggestion with the way that is working for me.

Thank you!

**Comment by donoghuc** [comment]
The example you pasted in here is just a snippet from the complete example in the docs https://github.com/puppetlabs/bolt/blob/main/documentation/supported_plugins.md#example-usage-2

The complete example is:
```yaml
targets:
  - _plugin: puppetdb
    query: "inventory[certname] { facts.osfamily = 'RedHat' }"
    target_mapping:
      alias: facts.hostname
      name: certname
      facts:
        custom_fact: facts.custom_fact
      features:
        - facts.custom_feature
      config:
        ssh:
          host: facts.networking.interfaces.en0.ipaddress
      vars:
        puppetversion: facts.puppetversion
```

The idea here was to show a real example of the the different places you can swap in values from pdb in creating targets. IN this case if we had swapped in `uri` instead of `name` in the top level of `target_mapping` then the `host` under `config.ssh` would not be respected. So in the context of the full example this would work. 

I am open to having another simpler example that does not attempt to demonstrate every single way to interpolate data, but I would like to keep the existing one as it is a good example of how to use every single key.
