### ISSUE TITLE
Versions in metadata.json do not follow the semver specification

### ISSUE THREAD

**Issue by abottchen** [puppetlabs/bolt#3214]
## Describe the Bug
If a version including a pre-release string is set in `metadata.json`, for example `5.0.0-beta1`, the `bolt module install` command will fail with:

```
# bolt module install
Installing project modules

  → Resolving module dependencies, this might take a moment

Unable to resolve modules: Puppetfile Resolver could not find compatible versions for possibility named "cd4pe":
  In Puppetfile:
    -cd4pe >= 0
``` 

## Expected Behavior
The version in `metadata.json` should allow all strings that conform with the semver specification.

## Steps to Reproduce
1. Set up a bolt project and add a module with the version set to include a pre-release string.  For example:

```
# cat bolt-project.yaml
---
name: cd4pe_bolt_project
modules:
 - git: https://github.com/puppetlabs/puppetlabs-cd4pe.git
   ref: '5.0.0-semvertest1'
```

2. Run `bolt module install`

## Environment
 - Version 3.27.1
 - Platform Ubuntu 20.04

## Additional Context
The semver specification at https://semver.org/spec/v1.0.0.html#spec-item-4 states that this specific naming convention is valid.  Assumption is that there is a problem in the underlying puppetfile-resolver library parsing the version number.
