### ISSUE TITLE
install module with ssh transport

### ISSUE THREAD

**Issue by mcarrolle** [puppetlabs/bolt#3237]
## Describe the Bug
Since bolt 3.25.0, we  can no longer install module from git private repository with SSH transport.
URIs starting with ssh:// are no longer accepted in the file bolt-project.yaml.
Returned error:
```
Invalid URI ssh://git@mygitlabserver:12345/namespace/myprivatemod.git. Valid URIs must begin with 'git@', 'http://', or 'https://'.
```
e.g bolt-project.yaml :
```
modules:
  - name: myprivatemod
    git: ssh://git@mygitlabserver:12345/namespace/myprivatemod.git
    ref: main
    resolve: false
```

## Expected Behavior
When running command `bolt module install` git repository is fetched with SSH transport.
