### ISSUE TITLE
Bolt can't find target by uri in inventory

### ISSUE THREAD

**Issue by dionysius** [puppetlabs/bolt#3344]
## Describe the Bug
Bolt returns a target by CLI and in a plan with `get_target()` or `get_targets()` whether it could find the target in the inventory or not.

https://www.puppet.com/docs/bolt/latest/inventory_files.html
> Similar to name, you can specify an alias as another way to refer to a target. In the following example, you **could run a command using the target's uri**, name, or alias.

While the documentation is technically true (it indeed does return a target, but not the expected one), this leads to an unexpected behaviour that any customisation is not reflected when getting this target. Any transport configuration, facts, custom vars, ... are not returned/used.

## Expected Behavior
CLI commands getting a target as well as bolt plan functions `get_target()` and `get_targets()` can find the target in the inventory by `uri` as well.

## Steps to Reproduce
1) Have a inventory.yaml setup
```yaml
targets:
  - uri: target1.example.com
    name: target1
    alias: dashboard
    config:
      transport: ssh
  - uri: target2.example.com
    name: target2
    alias: database
    config:
      transport: winrm
```
2) Observe the difference between those two commands:
```
$ bolt inventory show -t target2
Targets
  target2

Inventory source
  /home/dm/.puppetlabs/bolt/inventory.yaml

Target count
  1 total, 1 from inventory, 0 adhoc
```
```
$ bolt inventory show -t target2.example.com
Targets
  target2.example.com    (Not found in inventory file)

Inventory source
  /home/dm/.puppetlabs/bolt/inventory.yaml

Target count
  1 total, 0 from inventory, 1 adhoc
```
3) Transport config is lost
```
$ bolt inventory show -t target2 --detail | grep transport
    transport: winrm

$ bolt inventory show -t target2.example.com --detail | grep transport
    transport: ssh
```

## Environment
 - Version 3.30.0
 - Platform Debian

## Additional Context
A workaround using alias is also not sufficient for my case, as it can only be defined once.

I can see the use case of the current limitation. As you can define multiple targets for the same host (e.g. by using different ports) and thus "target != node".

> "When searching for a target's configuration data, Bolt matches a target's URI with its name. Bolt uses depth-first search and uses the first value it finds."

> "name	A human-readable name for a target. Required when specifying a target using a hash. Optional if using uri. If you don't specify a name, Bolt uses the uri as the target name."

The definition is unclear to me whether a target name represents its uri or not. If name is not defined, the uri is the name. So are those now considered equal or not?

Right now: If a name is defined a target in the inventory can only be found by name and alias. If no name is defined a target in the inventory can only be found by uri and alias. But you'll have to use two different names (or alias) if you use the same uri in multiple targets with different transport configuration.

> uri	The URI of the target. Bolt uses the uri to establish a connection to the target. Required when specifying a target using a hash, unless you specify a name and configure a hostname using host in the target's transport configuration.	

That sound right to me, define in transport.hostname any custom adaption of uri and port, but let the target be found by uri

### Additional Issue

If I only want a `get_target()` or `get_targets()` succeed if it's defined in the inventory, I have no feedback. If not double-checked a command could be executed on the wrong transport target.

**Comment by donoghuc** [comment]
In `Inventory` a `Target` name is a unique identifier. For this example:

```
targets:
  - uri: target1.example.com
    name: target1
    alias: dashboard
    config:
      transport: ssh
  - uri: target2.example.com
    name: target2
    alias: database
    config:
      transport: winrm
```
When you ask for `target2.example.com` you get a net new target as it does not match the `name` of any target.
`bolt inventory show -t target2.example.com` 

If you want `Target.name` and `Target.uri` to match, just specify `uri` and omit `name` from your inventory entreis. That will be the default `Target.name`.
