### ISSUE TITLE
Does inventoryfile support subgroups?

### ISSUE THREAD

**Issue by LongLiveCHIEF** [puppetlabs/bolt#367]
Can I use sub-groups in the inventory file?  The documentation isn't clear on if there is only one level supported, or if you can nest these.  

Lets say I currently have:
```
groups:
  - name: sandbox
    nodes:
      - sandbox1.example.com
      - sandbox2.example.com
      - sandbox3.example.com
      - sandbox4.example.com
      - sandbox5.example.com
      - sandbox6.example.com
  - name: production
    nodes:
      - prod1.example.com
```

Could I do something like this:

```
groups:
  - name: sandbox
    group:
      - name: app
        nodes:
           - sandbox1.example.com
           - sandbox2.example.com
      - name: web_server
        nodes:
           - sandbox3.example.com
           - sandbox4.example.com
     - name: db
       nodes:
          - sandbox5.example.com
          - sandbox6.example.com
  - name: production
    nodes: 
      - prod1.example.com
```

I know the obvious answer is "rename your hostnames", but let's assume that's not an option.
