### ISSUE TITLE
Allow user/password entry for WinRM in bolt.yaml

### ISSUE THREAD

**Issue by bbraunstein** [puppetlabs/bolt#448]
It'd be a nice add-in to support specifying the username/password for WinRM transport mode in the bolt.yaml config file. Instead of passing the `--user "${user}" --password "${password}"` each time needed to execute WInRM commands/tasks.

Perhaps allow the variables within the code block in the bolt.yaml file:
```
winrm:
  ssl: false
  user: <username>
  password: <password>
  connect-timeout: 30
```

Defaults would be specified parameters located in bolt.yaml, unless overridden by manually passed params on the CLI.
